### ISSUE TITLE
Update PHP score reading URL

### ISSUE THREAD

**Issue by sofiyakapasi** [traity/reputation-gateway-docs#1]
Hi Team,

Gone through the documentations and tried to integrate using `PHP` and it seems you forgot to have `https` in the url. Can you please update that. Here is the reference link https://reputation-gateway.readthedocs.io/en/latest/docs/contents/read_score.html

Corrected `$url`
```
<?php

  $url           = 'https://rg.traity.com/score';
```

Just replace `http://` => `https://` in `$url` and then it works

**Comment by dagi3d** [comment]
Thanks for the heads up @sofiyakapasi 
We just have updated the documentation. Please feel free to contact us if you find any other issue or need any help with the integration.

**Comment by sofiyakapasi** [comment]
@dagi3d Getting following response suddenly
```
{"error":{"type":"InternalError","description":"Internal server error"}}
```

What should be the root cause for this as it was working 2 days back. And now it is throwing internal server error.

Can you help me to figure this out as I have tried several options and no luck as of now.

Thanks.
